### ISSUE TITLE
Unable to update https://gitlab.com/sebk/tuple/

### ISSUE THREAD

**Issue by dngs** [pdf-rs/pdf#41]
why?
Unable to update https://gitlab.com/sebk/tuple/

**Comment by s3bk** [comment]
hm. I thought this was solved already.

**Comment by s3bk** [comment]
@dngs can you confirm that you are on the latest version (not the one published on crates.io)?

**Comment by dngs** [comment]
@s3bk 
Thanks!
I can sure that the rust and pdf-rs all are the latest version,but this issue remains.

**Comment by dngs** [comment]
@s3bk 
 cargo run -p view --release --bin pdf_view "C:\Users\tcm\Documents\Downloads\TheBrain 8 Transition Guide.pdf"
    Updating `https://code.aliyun.com/rustcc/crates.io-index.git` index
    Updating git repository `https://github.com/pdf-rs/encoding/`
    Updating git repository `https://github.com/s3bk/tuple`
    Updating git repository `https://github.com/pdf-rs/font/`
    Updating git repository `https://github.com/s3bk/pathfinder/`
    Updating git repository `https://github.com/s3bk/vector/`
    Updating git repository `https://gitlab.com/sebk/tuple/`
warning: spurious network error (2 tries remaining): request failed with status code: 308; class=Net (12)
warning: spurious network error (1 tries remaining): request failed with status code: 308; class=Net (12)
error: failed to load source for a dependency on `tuple`

Caused by:
  Unable to update https://gitlab.com/sebk/tuple/

Caused by:
  failed to fetch into C:\Users\tcm\.cargo\git\db\tuple-13774a280b73f454

Caused by:
  request failed with status code: 308; class=Net (12)

**Comment by s3bk** [comment]
@dngs I think it should be fixed now. please update `font` (or `cargo update`)

**Comment by dngs** [comment]
@s3bk 
Thank you very much!It has been fixed really!
However,the new issue occurs.As follows:
cargo run -p view --release --bin pdf_view
Compiling font v0.1.0 (https://github.com/pdf-rs/font/#945d399e)
error[E0554]: `#![feature]` may not be used on the stable release channel
--> C:\Users\tcm\.cargo\git\checkouts\font-06ada714b08e6cdd\945d399\src\lib.rs:1:1
|
1 | #![feature(thread_local)]
| ^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0554`.
error: could not compile `font`.

To learn more, run the command again with --verbose.

**Comment by s3bk** [comment]
thanks! should be fixed as well now.

**Comment by dngs** [comment]
@s3bk 
Thanks!Unfortunately, although the previous problem has been solved, the latest problem has come. As follows:
-------------------------------------------------------------------------------------------------------
 cargo run -p view --release --bin pdf_view "C:\Users\tcm\Documents\Downloads\TheBrain 8 Transition Guide.pdf"
   Compiling view v0.1.0 (D:\rust-pdf-master\view)
warning: variable does not need to be mutable
  --> view\src\bin\pdf_view.rs:57:9
   |
57 |     let mut window_size = (size * scale).to_i32();
   |         ----^^^^^^^^^^^
   |         |
   |         help: remove this `mut`
   |
   = note: `#[warn(unused_mut)]` on by default

warning: the `y:` in this pattern is redundant
   --> view\src\bin\pdf_view.rs:122:32
    |
122 |             Event::MouseWheel {y: y, .. } => {
    |                                --^^
    |                                |
    |                                help: remove this
    |
    = note: `#[warn(non_shorthand_field_patterns)]` on by default

error: linking with `link.exe` failed: exit code: 1181

**Comment by s3bk** [comment]
heh. I really need to set up automated tests on stable.

however those above are warnings. And… I have never tested on windows. make sure you have sdl installed: https://github.com/Rust-SDL2/rust-sdl2
